// Flags package: server definitions, assembled by definitions.js.
const FLAG_DEFINITIONS_SERVER = [
	// Server Settings
	{
		id: "host",
		flag: "--host",
		category: "server",
		type: "text",
		label: "Host",
		short_desc: "Network address the API server listens on.",
		desc: "IP address to listen on (default: 127.0.0.1)",
		tool: "server",
		default: "127.0.0.1",
	},
	{
		id: "port",
		flag: "--port",
		category: "server",
		type: "int",
		label: "Port",
		short_desc: "Port number for the API server.",
		beginner_tip: "Keep 8080 unless another app is already using it.",
		desc: "Port to listen on",
		tool: "server",
		default: 8080,
		min: 1,
		max: 65535,
	},
	{
		id: "alias",
		flag: "-a",
		category: "server",
		type: "text",
		label: "Model Alias",
		desc: "Model name alias(es) for the API (comma-separated)",
		tool: "server",
	},
	{
		id: "parallel",
		flag: "-np",
		category: "server",
		type: "int",
		label: "Parallel Slots",
		desc: "Number of server slots (-1 = auto)",
		tool: "server",
		default: -1,
		min: -1,
		max: 128,
		placeholder: "-1 = auto",
	},
	{
		id: "cont_batching",
		flag: "-cb",
		false_flag: "--no-cont-batching",
		category: "server",
		type: "bool",
		label: "Continuous Batching",
		desc: "Enable dynamic/continuous batching",
		tool: "server",
		default: true,
	},
	{
		id: "cache_prompt",
		flag: "--cache-prompt",
		false_flag: "--no-cache-prompt",
		category: "server",
		type: "bool",
		label: "Prompt Caching",
		desc: "Enable prompt caching",
		tool: "server",
		default: true,
	},
	{
		id: "cache_idle_slots",
		flag: "--cache-idle-slots",
		false_flag: "--no-cache-idle-slots",
		category: "server",
		type: "bool",
		label: "Cache Idle Slots",
		desc: "Save idle slots to the prompt cache when a new task arrives, and clear them when using unified KV (requires cache RAM)",
		tool: "server",
		default: true,
	},
	{
		id: "slot_save_path",
		flag: "--slot-save-path",
		category: "server",
		type: "path",
		label: "Slot Save Path",
		desc: "Directory where slot KV cache states can be saved and restored via the API (empty = disabled). The directory must already exist or the server will fail to start.",
		tool: "server",
	},
	{
		id: "slots_endpoint",
		flag: "--slots",
		false_flag: "--no-slots",
		category: "server",
		type: "bool",
		label: "Slots Endpoint",
		desc: "Expose the /slots monitoring endpoint for per-slot status",
		tool: "server",
		default: true,
	},
	{
		id: "timeout",
		flag: "-to",
		category: "server",
		type: "int",
		label: "Timeout (seconds)",
		desc: "Server read/write timeout",
		tool: "server",
		default: 3600,
		min: 1,
	},
	{
		id: "api_key",
		flag: "--api-key",
		category: "server",
		type: "text",
		label: "API Key",
		short_desc: "Optional key required for clients to access the API.",
		desc: "API key for authentication (comma-separated for multiple)",
		tool: "server",
		sensitive: true,
	},
	{
		id: "threads_http",
		flag: "--threads-http",
		category: "server",
		type: "int",
		label: "HTTP Threads",
		desc: "Threads for HTTP requests (-1 = auto)",
		tool: "server",
		min: -1,
	},
	{
		id: "metrics",
		flag: "--metrics",
		category: "server",
		type: "bool",
		label: "Prometheus Metrics",
		desc: "Enable Prometheus metrics endpoint",
		tool: "server",
		default: true,
	},
	{
		id: "webui",
		flag: "--webui",
		false_flag: "--no-webui",
		category: "server",
		type: "bool",
		label: "Web UI",
		short_desc: "Turns on the built-in browser interface.",
		desc: "Enable the built-in web UI",
		tool: "server",
		default: true,
	},
	{
		id: "webui_mcp_proxy",
		flag: "--ui-mcp-proxy",
		category: "mcp",
		type: "bool",
		label: "UI MCP Proxy",
		short_desc: "Enable MCP CORS proxy support for the Web UI.",
		desc: "Experimental. Allows the Web UI to proxy MCP requests via CORS. This replaces the deprecated --webui-mcp-proxy alias. Do not enable in untrusted environments.",
		tool: "server",
		default: false,
	},
	{
		id: "tools",
		flag: "--tools",
		category: "mcp",
		type: "multi_enum",
		label: "Built-in Tools",
		short_desc: "Enable local file/shell tools for AI agents in the Web UI.",
		beginner_tip:
			"Use 'all' only on trusted machines. In shared environments, list only what you need.",
		desc: "Experimental. Enables built-in agent tools exposed to the model through llama-server. Select one or more tools below, or choose 'all' to enable every tool.",
		tool: "server",
		options: [
			{ value: "all", label: "All tools", risk: "high" },
			{ value: "read_file", label: "Read File" },
			{ value: "file_glob_search", label: "File Glob Search" },
			{ value: "grep_search", label: "Grep Search" },
			{
				value: "exec_shell_command",
				label: "Exec Shell Command",
				risk: "high",
			},
			{ value: "write_file", label: "Write File", risk: "high" },
			{ value: "edit_file", label: "Edit File", risk: "high" },
			{ value: "get_info", label: "Get Runtime Info" },
		],
	},
	{
		id: "embedding",
		flag: "--embedding",
		category: "server",
		type: "bool",
		label: "Embedding Mode",
		desc: "Restrict to embedding use case only",
		tool: "server",
		default: false,
	},
	{
		id: "slot_prompt_similarity",
		flag: "-sps",
		category: "server",
		type: "float",
		label: "Slot Prompt Similarity",
		desc: "Prompt similarity threshold for slot reuse (0 = disabled)",
		tool: "server",
		default: 0.1,
		min: 0,
		max: 1,
		step: 0.01,
	},
	{
		id: "cache_reuse",
		flag: "--cache-reuse",
		category: "server",
		type: "int",
		label: "Cache Reuse Size",
		desc: "Min chunk size for cache reuse via KV shifting (0 = disabled)",
		tool: "server",
		default: 0,
		min: 0,
	},

	// Grammar & Constraints
	{
		id: "grammar",
		flag: "--grammar",
		category: "grammar",
		type: "text",
		label: "Grammar",
		desc: "BNF-like grammar to constrain generation",
		tool: "both",
	},
	{
		id: "grammar_file",
		flag: "--grammar-file",
		category: "grammar",
		type: "path",
		label: "Grammar File",
		desc: "File containing grammar rules",
		tool: "both",
	},
	{
		id: "json_schema",
		flag: "-j",
		category: "grammar",
		type: "text",
		label: "JSON Schema",
		desc: "JSON schema to constrain output, e.g. {}",
		tool: "both",
	},
	{
		id: "json_schema_file",
		flag: "-jf",
		category: "grammar",
		type: "path",
		label: "JSON Schema File",
		desc: "File containing a JSON schema",
		tool: "both",
	},
	{
		id: "backend_sampling",
		flag: "-bs",
		category: "grammar",
		type: "bool",
		label: "Backend Sampling",
		desc: "Enable backend sampling (experimental)",
		tool: "both",
		default: false,
	},

	// Logging
	{
		id: "verbose",
		flag: "-v",
		category: "logging",
		type: "bool",
		label: "Verbose",
		desc: "Set verbosity to maximum (log all messages)",
		tool: "both",
		default: false,
	},
	{
		id: "verbosity",
		flag: "-lv",
		category: "logging",
		type: "int",
		label: "Verbosity Level",
		desc: "Log verbosity threshold (0=generic, 1=error, 2=warn, 3=info, 4=debug)",
		tool: "both",
		default: 3,
		min: 0,
		max: 4,
	},
	{
		id: "log_file",
		flag: "--log-file",
		category: "logging",
		type: "path",
		label: "Log File",
		desc: "Write logs to file",
		tool: "both",
	},
	{
		id: "log_colors",
		flag: "--log-colors",
		category: "logging",
		type: "enum",
		label: "Log Colors",
		desc: "Colored logging",
		tool: "both",
		default: "auto",
		options: [
			{ value: "auto", label: "Auto (default)" },
			{ value: "on", label: "On" },
			{ value: "off", label: "Off" },
		],
	},
	{
		id: "log_prefix",
		flag: "--log-prefix",
		category: "logging",
		type: "bool",
		label: "Log Prefix",
		desc: "Enable prefix in log messages",
		tool: "both",
		default: false,
	},
	{
		id: "log_timestamps",
		flag: "--log-timestamps",
		category: "logging",
		type: "bool",
		label: "Log Timestamps",
		desc: "Enable timestamps in log messages",
		tool: "both",
		default: false,
	},
	{
		id: "show_timings",
		flag: "--show-timings",
		false_flag: "--no-show-timings",
		category: "logging",
		type: "bool",
		label: "Show Timings",
		desc: "Show timing information after each response",
		tool: "cli",
		default: true,
	},

	// Advanced
	{
		id: "tensor_read_lazy",
		flag: "--lazy-mode",
		category: "advanced",
		type: "enum",
		label: "Lazy Mode",
		short_desc: "Read eligible model tensors from disk on demand to reduce resident RAM use.",
		desc: "Controls on-demand reading for tensors marked as eligible by the model architecture, such as large per-layer embedding tables. Requires mmap. Auto uses llama.cpp's default behavior (lazy only above 4 GiB); On trades some inference speed for lower resident RAM; Off keeps eligible tensors resident.",
		tool: "both",
		default: "",
		options: [
			{ value: "", label: "Auto (Recommended)" },
			{ value: "on", label: "On (Lower RAM)" },
			{ value: "off", label: "Off (Keep Resident)" },
		],
	},
	{
		id: "override_kv",
		flag: "--override-kv",
		category: "advanced",
		type: "text",
		label: "Override KV Metadata",
		desc: "Override model metadata, e.g. KEY=TYPE:VALUE,...",
		tool: "both",
	},
	{
		id: "override_tensor",
		flag: "-ot",
		category: "advanced",
		type: "text",
		label: "Tensor Buffer Overrides",
		short_desc:
			"Force matching model tensors onto a specific backend buffer, such as CPU or CUDA0.",
		desc: "Expert override tensor memory-placement control. Format: pattern=BUFFER, comma-separated for multiple overrides. The pattern matches GGUF/on-disk tensor names, commonly with regex-style escaping, and BUFFER must match a buffer type reported by the installed backend, such as CPU or CUDA0. The experimental MoE expert helper applies to MoE models only; it assigns expert weight tensors, not the runtime-active experts chosen for a prompt. A common MoE use is keeping expert tensors on CPU while offloading the rest of the model to GPU, or explicitly placing expert tensors on a GPU buffer. GPU/accelerator MoE helper targets clear CPU MoE settings to avoid conflicting expert placement overrides. Enable verbose logging (-v) to confirm which tensors matched. Bad patterns or buffer names can fail launch or create poor memory/performance behavior.",
		tool: "both",
		placeholder: "blk.*.ffn_.*_exps.weight=CPU",
	},
	{
		id: "check_tensors",
		flag: "--check-tensors",
		category: "advanced",
		type: "bool",
		label: "Check Tensors",
		desc: "Check model tensor data for invalid values",
		tool: "both",
		default: false,
	},
	{
		id: "no_host",
		flag: "--no-host",
		category: "advanced",
		type: "bool",
		label: "No Host Buffer",
		desc: "Bypass host buffer for extra buffers",
		tool: "both",
		default: false,
	},
	{
		id: "warmup",
		flag: "--warmup",
		false_flag: "--no-warmup",
		category: "advanced",
		type: "bool",
		label: "Warmup",
		desc: "Perform warmup with empty run",
		tool: "both",
		default: true,
	},
	{
		id: "offline",
		flag: "--offline",
		category: "advanced",
		type: "bool",
		label: "Offline Mode",
		desc: "Force cache use, prevent network access",
		tool: "both",
		default: false,
	},

	// Experimental
	{
		id: "spec_draft_adaptive",
		flag: "--spec-draft-adaptive",
		category: "experimental",
		type: "bool",
		label: "Adaptive Draft Size",
		desc: "Size each speculative draft from measured acceptance instead of always drafting --spec-draft-n-max tokens. Available in the LaurentZuijdwijk llama.cpp fork; upstream builds may reject this flag.",
		tool: "both",
		default: false,
		// Fork-only on purpose (docs/upstream-changes.md): the installed-binary
		// compatibility check never holds this flag against upstream builds.
		fork_only: true,
	},
];
