const FLAGS = [
	// Model
	{
		id: "hf_repo",
		flag: "-hf",
		category: "model",
		type: "text",
		label: "HF 仓库",
		short_desc: "用 仓库名/模型名 直接从 Hugging Face 加载模型。",
		desc: "HF 仓库：用户/模型[:量化]，例如 ggml-org/gemma-3-1b-it-GGUF:Q4_K_M",
		tool: "both",
	},
	{
		id: "hf_file",
		flag: "-hff",
		category: "model",
		type: "text",
		label: "HF 文件覆盖",
		desc: "从 HF 仓库中指定具体的 GGUF 文件",
		tool: "both",
	},
	{
		id: "hf_token",
		flag: "-hft",
		category: "model",
		type: "text",
		label: "HF 令牌",
		desc: "Hugging Face 访问令牌（或设置 HF_TOKEN 环境变量）",
		tool: "both",
	},
	{
		id: "model_draft",
		flag: "-md",
		category: "model",
		type: "path",
		label: "草稿模型",
		desc: "投机解码用的草稿模型",
		tool: "both",
	},
	{
		id: "hf_repo_draft",
		flag: "-hfd",
		category: "model",
		type: "text",
		label: "HF 草稿仓库",
		desc: "草稿模型的 HF 仓库",
		tool: "both",
	},
	{
		id: "mmproj",
		flag: "-mm",
		category: "model",
		type: "path",
		label: "多模态投影器",
		desc: "mmproj 投影文件路径（视觉模型用）",
		tool: "both",
	},
	{
		id: "mmproj_device",
		flag: "--mmproj-device",
		category: "model",
		type: "text",
		label: "投影器设备",
		short_desc: "选择运行多模态投影器的后端设备。",
		desc: "为多模态投影器选择一个后端设备，例如主模型在独显上、投影器放核显。使用 --list-devices 列出的名称；只接受一个设备，留空则不卸载投影器。短别名 -mmdev。llama.cpp b10541 与 v0.2.0+ 可用。",
		tool: "both",
		placeholder: "auto; none = don't offload",
	},
	{
		id: "mmproj_url",
		flag: "--mmproj-url",
		category: "model",
		type: "text",
		label: "投影器 URL",
		desc: "多模态投影文件的 URL。本地 HF 下载行为不变。",
		tool: "both",
	},
	{
		id: "image_min_tokens",
		flag: "--image-min-tokens",
		category: "model",
		type: "int",
		label: "图像最小 Token",
		desc: "动态分辨率视觉模型中每张图像的最小 Token 数。-1 表示读取模型内置值。",
		tool: "both",
		default: -1,
		min: -1,
	},
	{
		id: "image_max_tokens",
		flag: "--image-max-tokens",
		category: "model",
		type: "int",
		label: "图像最大 Token",
		desc: "动态分辨率视觉模型中每张图像的最大 Token 数。-1 表示读取模型内置值。",
		tool: "both",
		default: -1,
		min: -1,
	},
	{
		id: "mtmd_batch_max_tokens",
		flag: "--mtmd-batch-max-tokens",
		category: "model",
		type: "int",
		label: "多模态批上限 Token",
		desc: "编码图像时每批的最大图像 Token 数。",
		tool: "server",
		default: 1024,
		min: 1,
	},
	{
		id: "no_mmproj",
		flag: "--no-mmproj",
		category: "model",
		type: "bool",
		label: "禁用 mmproj 自动下载",
		desc: "使用 -hf 时禁用 mmproj 自动下载",
		tool: "both",
		default: false,
	},

	// Context & Memory
	{
		id: "ctx_size",
		flag: "-c",
		category: "context",
		type: "int",
		label: "总上下文窗口",
		short_desc: "模型一次能在内存里记住的文本量。",
		beginner_tip:
			"64000 is a strong default. Lower it if you run out of memory.",
		desc: "总上下文大小（Token 数）。这是模型一次能'记住'的最大 Token 量，包括你的提示、系统提示、对话历史和模型的回复。值越大占用显存/内存越多。填 0 使用模型默认值。",
		tool: "both",
		default: 64000,
		min: 0,
		max: 262144,
		placeholder: "64000 recommended",
	},
	{
		id: "batch_size",
		flag: "-b",
		category: "context",
		type: "int",
		label: "提示批大小",
		short_desc: "越高读取提示越快，但占用内存越多。",
		beginner_tip:
			"If you hit memory errors while loading prompts, lower this value first.",
		desc: "提示词读取阶段并行处理的 Token 上限（决定提示被读多快）。越高提示处理越快但占用内存越多。只影响提示速度，不影响生成速度。",
		tool: "both",
		default: 2048,
		min: 1,
		max: 8192,
	},
	{
		id: "ubatch_size",
		flag: "-ub",
		category: "context",
		type: "int",
		label: "物理批大小",
		short_desc: "遇到内存不足时优先调低这一项。",
		desc: "内部 GPU/CPU 批大小。应不大于逻辑批大小。调低省显存但可能变慢。一般保持默认，除非遇到内存不足报错。",
		tool: "both",
		default: 512,
		min: 1,
		max: 4096,
	},
	{
		id: "n_predict",
		flag: "-n",
		category: "context",
		type: "int",
		label: "每条回复最大 Token",
		short_desc: "限制每条回复的最大长度。",
		desc: "模型每条回复最多生成的 Token 数。-1 表示不限制（一直生成到出现结束符或占满上下文）。可用来防止无限生成。",
		tool: "both",
		default: -1,
		min: -1,
		max: 131072,
		placeholder: "-1 = unlimited",
	},
	{
		id: "keep",
		flag: "--keep",
		category: "context",
		type: "int",
		label: "保留开头 Token 数",
		desc: "上下文占满时，从对话开头（系统提示 + 最早消息）永久保留多少 Token。0 = 全部丢弃，-1 = 全部保留。",
		tool: "both",
		default: 0,
		min: -1,
	},
	{
		id: "mlock",
		flag: "--mlock",
		category: "context",
		type: "bool",
		label: "锁定内存",
		desc: "已被 llama.cpp 的 --load-mode mlock 取代。强制系统把内存映射的模型留在物理内存中，不换出到磁盘。",
		tool: "both",
		default: false,
	},
	{
		id: "mmap",
		flag: "--mmap",
		false_flag: "--no-mmap",
		category: "context",
		type: "bool",
		label: "内存映射加载",
		desc: "已被 llama.cpp 的 --load-mode mmap 取代。用内存映射文件加载模型，加载更快、内存占用更低。",
		tool: "both",
		default: false,
	},
	{
		id: "direct_io",
		flag: "-dio",
		category: "context",
		type: "bool",
		label: "直接 I/O",
		desc: "已被 llama.cpp 的 --load-mode dio 取代。在支持时绕过系统页缓存直接读取模型。",
		tool: "both",
		default: false,
	},
	{
		id: "load_mode",
		flag: "--load-mode",
		category: "context",
		type: "enum",
		label: "模型加载模式",
		short_desc: "选择 llama.cpp 的模型加载策略。",
		desc: "旧版 mmap/mlock/直接 I/O 开关的推荐替代。选择某个模式后，生成命令将不再带上那些旧参数。",
		tool: "both",
		default: "mmap",
		options: [
			{ value: "", label: "旧版开关（由加载模式取代）" },
			{ value: "none", label: "无" },
			{ value: "mmap", label: "内存映射" },
			{ value: "mlock", label: "内存映射 + 锁定" },
			{ value: "dio", label: "直接 I/O" },
		],
	},
	{
		id: "swa_full",
		flag: "--swa-full",
		category: "context",
		type: "bool",
		label: "完整 SWA 缓存",
		desc: "使用完整大小的滑动窗口注意力缓存而非压缩版。占用更多内存，但保留完整上下文质量。",
		tool: "both",
		default: false,
	},
	{
		id: "cache_ram",
		flag: "-cram",
		category: "context",
		type: "int",
		label: "KV 缓存内存上限（MiB）",
		desc: "KV 缓存可用的最大内存/显存（MiB）。KV 缓存存放对话历史——缓存越大，越久的历史能被保留。-1 = 不限制，0 = 禁用。",
		tool: "both",
		default: 8192,
		min: -1,
		placeholder: "-1 unlimited",
	},
	{
		id: "ctx_checkpoints",
		flag: "-ctxcp",
		category: "context",
		type: "int",
		label: "上下文检查点",
		short_desc:
			"为长提示保存可复用的快照，让后续请求少重复处理上下文。",
		desc: "每个服务器槽位最多创建的上下文检查点数。调高可改善长对话或代理工作流的提示缓存复用，但占用更多内存。填 0 禁用。",
		tool: "server",
		default: 32,
		min: 0,
	},
	{
		id: "checkpoint_every_n_tokens",
		flag: "-cms",
		category: "context",
		type: "int",
		label: "检查点最小间隔",
		short_desc: "设置上下文检查点之间的最小 Token 间隔。",
		desc: "上下文检查点之间的最小 Token 间隔。0 = 不设最小间隔。要完全禁用检查点，把上下文检查点数（-ctxcp）设为 0。",
		tool: "server",
		default: 256,
		min: 0,
		placeholder: "0 = no minimum",
	},

	// CPU & Threads
	{
		id: "threads",
		flag: "-t",
		category: "cpu",
		type: "int",
		label: "生成线程数",
		short_desc: "生成时使用的 CPU 线程数（-1 自动选择）。",
		desc: "生成阶段使用的 CPU 线程数（-1 = 自动）",
		tool: "both",
		default: -1,
		min: -1,
		max: 256,
		placeholder: "-1 = auto",
	},
	{
		id: "threads_batch",
		flag: "-tb",
		category: "cpu",
		type: "int",
		label: "批处理线程",
		desc: "批处理/提示处理线程数（默认与生成线程相同）",
		tool: "both",
		min: -1,
		max: 256,
		placeholder: "default = threads",
	},
	{
		id: "cpu_mask",
		flag: "-C",
		category: "cpu",
		type: "text",
		label: "CPU 亲和掩码",
		desc: "CPU 亲和掩码（十六进制）",
		tool: "both",
	},
	{
		id: "cpu_range",
		flag: "-Cr",
		category: "cpu",
		type: "text",
		label: "CPU 范围",
		desc: "CPU 亲和范围，例如 0-7",
		tool: "both",
	},
	{
		id: "numa",
		flag: "--numa",
		category: "cpu",
		type: "enum",
		label: "NUMA 模式",
		desc: "NUMA 优化类型",
		tool: "both",
		options: [
			{ value: "", label: "禁用" },
			{ value: "distribute", label: "分配" },
			{ value: "isolate", label: "隔离" },
			{ value: "numactl", label: "numactl 绑定" },
		],
	},
	{
		id: "prio",
		flag: "--prio",
		category: "cpu",
		type: "enum",
		label: "线程优先级",
		desc: "进程/线程优先级",
		tool: "both",
		options: [
			{ value: "0", label: "普通（0）" },
			{ value: "-1", label: "低（-1）" },
			{ value: "1", label: "中（1）" },
			{ value: "2", label: "高（2）" },
			{ value: "3", label: "实时（3）" },
		],
	},
	{
		id: "poll",
		flag: "--poll",
		category: "cpu",
		type: "int",
		label: "轮询级别",
		desc: "等待任务时的轮询级别（0 = 不轮询）",
		tool: "both",
		default: 50,
		min: 0,
		max: 100,
	},

	// GPU / Acceleration
	{
		id: "gpu_layers",
		flag: "-ngl",
		category: "gpu",
		type: "text",
		label: "GPU 层数",
		short_desc: "模型有多少放进 GPU。",
		beginner_tip: "Leave on auto unless you are tuning performance manually.",
		desc: "放进显存的最大层数（数字、'auto' 或 'all'）",
		tool: "both",
		default: "auto",
		placeholder: "auto",
	},
	{
		id: "split_mode",
		flag: "-sm",
		category: "gpu",
		type: "enum",
		label: "多 GPU 切分方式",
		desc: "多 GPU 间如何切分模型",
		tool: "both",
		options: [
			{ value: "layer", label: "按层（默认）" },
			{ value: "none", label: "无" },
			{ value: "row", label: "按行" },
			{ value: "tensor", label: "张量" },
		],
	},
	{
		id: "tensor_split",
		flag: "-ts",
		category: "gpu",
		type: "text",
		label: "显存切分比例",
		desc: "各 GPU 分到的比例，逗号分隔，例如 3,1",
		tool: "both",
	},
	{
		id: "main_gpu",
		flag: "-mg",
		category: "gpu",
		type: "int",
		label: "主 GPU",
		desc: "用于模型/中间结果的 GPU",
		tool: "both",
		default: 0,
		min: 0,
	},
	{
		id: "device",
		flag: "-dev",
		category: "gpu",
		type: "text",
		label: "设备",
		desc: "卸载目标设备列表，逗号分隔",
		tool: "both",
		placeholder: "none = don't offload",
	},
	{
		id: "flash_attn",
		flag: "-fa",
		category: "gpu",
		type: "enum",
		label: "Flash 注意力",
		desc: "Flash 注意力模式",
		tool: "both",
		default: "auto",
		options: [
			{ value: "auto", label: "自动（默认）" },
			{ value: "on", label: "开" },
			{ value: "off", label: "关" },
		],
	},
	{
		id: "kv_offload",
		flag: "-kvo",
		false_flag: "--no-kv-offload",
		category: "gpu",
		type: "bool",
		label: "KV 缓存上 GPU",
		desc: "启用 KV 缓存卸载",
		tool: "both",
		default: true,
	},
	{
		id: "repack",
		flag: "--repack",
		false_flag: "--no-repack",
		category: "gpu",
		type: "bool",
		label: "权重重排",
		desc: "启用权重重排",
		tool: "both",
		default: false,
	},
	{
		id: "op_offload",
		flag: "--op-offload",
		false_flag: "--no-op-offload",
		category: "gpu",
		type: "bool",
		label: "运算卸载",
		desc: "在设备支持时把主机侧张量运算也卸载过去。",
		tool: "both",
		default: true,
	},
	{
		id: "fit",
		flag: "-fit",
		category: "auto_fit",
		type: "enum",
		label: "自动适配显存",
		short_desc:
			"自动调低未手动设置的重内存选项，降低显存不足导致崩溃的概率。",
		beginner_tip: "Keep this ON unless you specifically need manual control.",
		desc: "自动适配总开关。开启后 llama.cpp 可能调低未手动设置的上下文/批大小等值，让模型装进可用显存。它不替代下面的辅助设置：-fitt 设必须保留的空闲显存，-fitc 设上下文下限。",
		tool: "both",
		default: "on",
		options: [
			{ value: "on", label: "开（推荐）" },
			{ value: "off", label: "关" },
		],
	},
	{
		id: "fit_target",
		flag: "-fitt",
		category: "auto_fit",
		type: "text",
		label: "适配目标余量",
		short_desc:
			"告诉自动适配每张卡要预留多少空闲显存作缓冲。",
		beginner_tip:
			"Leave this alone unless auto-fit is still too aggressive for your system.",
		desc: "自动适配的安全余量（MiB）。越高越保守（留更多空闲显存），越低塞得越满。它不覆盖 -fit/-fitc，只是收窄自动适配可以占用的范围。",
		tool: "both",
		default: "1024",
		placeholder: "1024 or 1024,2048",
	},
	{
		id: "fit_ctx",
		flag: "-fitc",
		category: "auto_fit",
		type: "int",
		label: "自动适配最小上下文",
		short_desc:
			"设置自动适配允许降到的最小上下文窗口。",
		beginner_tip:
			"Raise this only if you need a guaranteed minimum context and have enough VRAM to support it.",
		desc: "自动适配允许选到的最小上下文。把它当作下限，而不是替代你平时的上下文设置：-fit 仍自行决定是否调整内存相关设置，这里只限制上下文最低能降到多少。",
		tool: "both",
		default: 64000,
		min: 0,
		max: 262144,
		placeholder: "64000",
	},
	{
		id: "cpu_moe",
		flag: "-cmoe",
		category: "gpu",
		type: "bool",
		label: "MoE 全留 CPU",
		desc: "全部 MoE 权重留在 CPU",
		tool: "both",
		default: false,
	},
	{
		id: "n_cpu_moe",
		flag: "-ncmoe",
		category: "gpu",
		type: "int",
		label: "CPU MoE 层数",
		desc: "前 N 层的 MoE 权重留在 CPU",
		tool: "both",
		min: 0,
	},
	{
		id: "n_cpu_ffn",
		flag: "-ncffn",
		category: "gpu",
		type: "int",
		label: "CPU FFN 层数",
		desc: "前 N 层的稠密 FFN 权重留在 CPU",
		tool: "both",
		min: 0,
	},
	{
		id: "mmproj_offload",
		flag: "--mmproj-offload",
		false_flag: "--no-mmproj-offload",
		category: "gpu",
		type: "bool",
		label: "mmproj 上 GPU",
		desc: "启用多模态投影器的 GPU 卸载",
		tool: "both",
		default: true,
	},

	// Sampling
	{
		id: "temperature",
		flag: "--temp",
		category: "sampling",
		type: "float",
		label: "温度",
		short_desc: "控制发散程度：越低越专注，越高越随机。",
		beginner_tip: "Try 0.7-0.9 for general chat. Lower for factual tasks.",
		desc: "采样温度（越高越随机）",
		tool: "both",
		default: 0.8,
		min: 0,
		max: 5,
		step: 0.01,
	},
	{
		id: "top_k",
		flag: "--top-k",
		category: "sampling",
		type: "int",
		label: "Top-K",
		short_desc: "只在概率最高的 K 个候选里选择。",
		desc: "只从概率前 K 的 Token 中选择（0 = 关闭）",
		tool: "both",
		default: 40,
		min: 0,
		max: 1000,
	},
	{
		id: "top_p",
		flag: "--top-p",
		category: "sampling",
		type: "float",
		label: "Top-P",
		short_desc:
			"按累计概率只保留概率最高的那组候选。",
		beginner_tip: "0.9-0.95 is a safe range for most chat use.",
		desc: "核采样阈值（1.0 = 关闭）",
		tool: "both",
		default: 0.95,
		min: 0,
		max: 1,
		step: 0.01,
	},
	{
		id: "min_p",
		flag: "--min-p",
		category: "sampling",
		type: "float",
		label: "Min-P",
		short_desc: "剔除概率极低的候选，让输出更稳定。",
		desc: "相对最高概率 Token 的最小概率（0 = 关闭）",
		tool: "both",
		default: 0.05,
		min: 0,
		max: 1,
		step: 0.01,
	},
	{
		id: "top_n_sigma",
		flag: "--top-n-sigma",
		category: "sampling",
		type: "float",
		label: "Top-N-Sigma",
		desc: "Top-N-Sigma 采样（-1 = 关闭）",
		tool: "both",
		default: -1,
		min: -1,
		max: 10,
		step: 0.01,
		submenu: "高级截断",
	},
	{
		id: "xtc_probability",
		flag: "--xtc-probability",
		category: "sampling",
		type: "float",
		label: "XTC 移除概率",
		desc: "XTC 移除 Token 的概率（0 = 关闭）",
		tool: "both",
		min: 0,
		max: 1,
		step: 0.01,
		submenu: "XTC 采样",
	},
	{
		id: "xtc_threshold",
		flag: "--xtc-threshold",
		category: "sampling",
		type: "float",
		label: "XTC 阈值",
		desc: "XTC 阈值（1.0 = 关闭）",
		tool: "both",
		min: 0,
		max: 1,
		step: 0.01,
		submenu: "XTC 采样",
	},
	{
		id: "typical_p",
		flag: "--typical-p",
		category: "sampling",
		type: "float",
		label: "Typical-P",
		desc: "局部典型性采样（1.0 = 关闭）",
		tool: "both",
		default: 1.0,
		min: 0,
		max: 1,
		step: 0.01,
		submenu: "高级截断",
	},
	{
		id: "repeat_last_n",
		flag: "--repeat-last-n",
		category: "sampling",
		type: "int",
		label: "重复惩罚窗口",
		desc: "重复惩罚回看窗口（0 = 关闭，-1 = 整个上下文）",
		tool: "both",
		default: 64,
		min: -1,
		submenu: "重复惩罚",
	},
	{
		id: "repeat_penalty",
		flag: "--repeat-penalty",
		category: "sampling",
		type: "float",
		label: "重复惩罚",
		short_desc: "抑制模型重复自己。",
		beginner_tip:
			"If replies loop or repeat phrases, raise this slightly above 1.0.",
		desc: "惩罚重复 Token 序列（1.0 = 关闭）",
		tool: "both",
		default: 1.0,
		min: 0.5,
		max: 3,
		step: 0.01,
	},
	{
		id: "presence_penalty",
		flag: "--presence-penalty",
		category: "sampling",
		type: "float",
		label: "存在惩罚",
		desc: "存在惩罚（0 = 关闭）",
		tool: "both",
		default: 0,
		min: 0,
		max: 5,
		step: 0.1,
	},
	{
		id: "frequency_penalty",
		flag: "--frequency-penalty",
		category: "sampling",
		type: "float",
		label: "频率惩罚",
		desc: "频率惩罚（0 = 关闭）",
		tool: "both",
		default: 0,
		min: 0,
		max: 5,
		step: 0.05,
		submenu: "重复惩罚",
	},
	{
		id: "dry_multiplier",
		flag: "--dry-multiplier",
		category: "sampling",
		type: "float",
		label: "DRY 惩罚倍率",
		desc: "DRY 重复惩罚倍率（0 = 关闭）",
		tool: "both",
		default: 0,
		min: 0,
		max: 5,
		step: 0.05,
		submenu: "DRY 采样",
	},
	{
		id: "dry_base",
		flag: "--dry-base",
		category: "sampling",
		type: "float",
		label: "DRY 基数",
		desc: "DRY 惩罚指数的基数",
		tool: "both",
		default: 1.75,
		min: 1,
		max: 5,
		step: 0.05,
		submenu: "DRY 采样",
	},
	{
		id: "dry_allowed_length",
		flag: "--dry-allowed-length",
		category: "sampling",
		type: "int",
		label: "DRY 允许长度",
		desc: "DRY 生效前允许的最大重复长度",
		tool: "both",
		default: 2,
		min: 1,
		submenu: "DRY 采样",
	},
	{
		id: "dry_penalty_last_n",
		flag: "--dry-penalty-last-n",
		category: "sampling",
		type: "int",
		label: "DRY 惩罚历史",
		desc: "DRY 回扫最近多少 Token 来发现重复序列（0 = 关闭，-1 = 整个上下文）。",
		tool: "both",
		default: -1,
		min: -1,
		submenu: "DRY 采样",
	},
	{
		id: "dry_sequence_breakers",
		flag: "--dry-sequence-breaker",
		category: "sampling",
		type: "text_list",
		label: "DRY 序列打断符",
		short_desc: "每行填一个序列打断符。",
		desc: "留空保留 llama.cpp 默认（换行、冒号、双引号、星号）。填写任意条目将整体替换默认；单独填 none 关闭所有序列打断符。",
		beginner_tip: "Custom breakers replace the defaults. If you still want the defaults, include them explicitly along with your additions.",
		tool: "both",
		default: [],
		placeholder: "One breaker per line, e.g. —",
		submenu: "DRY 采样",
	},
	{
		id: "dynatemp_range",
		flag: "--dynatemp-range",
		category: "sampling",
		type: "float",
		label: "动态温度范围",
		desc: "动态温度范围（0 = 关闭）",
		tool: "both",
		default: 0,
		min: 0,
		max: 5,
		step: 0.01,
		submenu: "动态温度",
	},
	{
		id: "dynatemp_exp",
		flag: "--dynatemp-exp",
		category: "sampling",
		type: "float",
		label: "动态温度指数",
		desc: "动态温度指数",
		tool: "both",
		default: 1.0,
		min: 0.1,
		max: 5,
		step: 0.05,
		submenu: "动态温度",
	},
	{
		id: "mirostat",
		flag: "--mirostat",
		category: "sampling",
		type: "enum",
		label: "Mirostat",
		desc: "Mirostat 采样模式",
		tool: "both",
		options: [
			{ value: "0", label: "禁用（0）" },
			{ value: "1", label: "Mirostat（1）" },
			{ value: "2", label: "Mirostat 2.0（2）" },
		],
		submenu: "Mirostat",
	},
	{
		id: "mirostat_lr",
		flag: "--mirostat-lr",
		category: "sampling",
		type: "float",
		label: "Mirostat 学习率",
		desc: "Mirostat 学习率（eta）",
		tool: "both",
		min: 0.001,
		max: 1,
		step: 0.01,
		submenu: "Mirostat",
	},
	{
		id: "mirostat_ent",
		flag: "--mirostat-ent",
		category: "sampling",
		type: "float",
		label: "Mirostat 目标熵",
		desc: "Mirostat 目标熵（tau）",
		tool: "both",
		min: 0,
		max: 20,
		step: 0.1,
		submenu: "Mirostat",
	},
	{
		id: "seed",
		flag: "-s",
		category: "sampling",
		type: "int",
		label: "随机种子",
		short_desc: "固定种子可获得可复现的输出。",
		desc: "随机种子（-1 = 随机）",
		tool: "both",
		default: -1,
		min: -1,
		placeholder: "-1 = random",
		submenu: "生成控制",
	},
	{
		id: "ignore_eos",
		flag: "--ignore-eos",
		category: "sampling",
		type: "bool",
		label: "忽略结束符",
		desc: "忽略结束符继续生成",
		tool: "both",
		default: false,
		submenu: "生成控制",
	},
	{
		id: "samplers",
		flag: "--samplers",
		category: "sampling",
		type: "text",
		label: "采样器序列",
		desc: "自定义采样器顺序，分号分隔",
		tool: "both",
		placeholder: "penalties;dry;top_k;top_p;temperature",
		submenu: "采样器顺序",
	},
	{
		id: "sampler_seq",
		flag: "--sampler-seq",
		category: "sampling",
		type: "text",
		label: "采样器序列（简写）",
		desc: "简化的采样器序列简写。使用上方高级采样器顺序时请留空。",
		tool: "both",
		placeholder: "edskypmxt",
		submenu: "采样器顺序",
	},

	// RoPE Scaling
	{
		id: "rope_scaling",
		flag: "--rope-scaling",
		category: "rope",
		type: "enum",
		label: "RoPE 缩放方式",
		desc: "RoPE 频率缩放方式",
		tool: "both",
		options: [
			{ value: "", label: "默认（跟随模型）" },
			{ value: "none", label: "无" },
			{ value: "linear", label: "线性" },
			{ value: "yarn", label: "YaRN" },
		],
	},
	{
		id: "rope_scale",
		flag: "--rope-scale",
		category: "rope",
		type: "float",
		label: "RoPE 缩放",
		desc: "上下文缩放系数（扩展 N 倍）",
		tool: "both",
		min: 0,
		step: 0.1,
	},
	{
		id: "rope_freq_base",
		flag: "--rope-freq-base",
		category: "rope",
		type: "float",
		label: "RoPE 基频",
		desc: "NTK 感知缩放的 RoPE 基频",
		tool: "both",
		min: 0,
		step: 100,
	},
	{
		id: "rope_freq_scale",
		flag: "--rope-freq-scale",
		category: "rope",
		type: "float",
		label: "RoPE 频率缩放",
		desc: "RoPE 频率缩放系数（按 1/N 扩展）",
		tool: "both",
		min: 0,
		step: 0.01,
	},
	{
		id: "yarn_orig_ctx",
		flag: "--yarn-orig-ctx",
		category: "rope",
		type: "int",
		label: "YaRN 原始上下文",
		desc: "原始上下文大小（0 = 跟随模型）",
		tool: "both",
		default: 0,
		min: 0,
	},
	{
		id: "yarn_ext_factor",
		flag: "--yarn-ext-factor",
		category: "rope",
		type: "float",
		label: "YaRN 外推混合",
		desc: "YaRN 外推混合系数",
		tool: "both",
		default: -1,
		min: -1,
		max: 1,
		step: 0.01,
	},
	{
		id: "yarn_attn_factor",
		flag: "--yarn-attn-factor",
		category: "rope",
		type: "float",
		label: "YaRN 注意力幅度",
		desc: "YaRN 注意力幅度缩放",
		tool: "both",
		default: -1,
		min: -1,
		max: 2,
		step: 0.01,
	},
	{
		id: "yarn_beta_slow",
		flag: "--yarn-beta-slow",
		category: "rope",
		type: "float",
		label: "YaRN Beta 低维",
		desc: "YaRN 高维修正",
		tool: "both",
		default: -1,
		min: -1,
		step: 0.01,
	},
	{
		id: "yarn_beta_fast",
		flag: "--yarn-beta-fast",
		category: "rope",
		type: "float",
		label: "YaRN Beta 高维",
		desc: "YaRN 低维修正",
		tool: "both",
		default: -1,
		min: -1,
		step: 0.01,
	},

	// Conversation & Chat
	{
		id: "conversation",
		flag: "-cnv",
		category: "conversation",
		type: "bool",
		label: "对话模式",
		desc: "以交互对话模式运行",
		tool: "cli",
		default: false,
	},
	{
		id: "system_prompt",
		flag: "-sys",
		category: "conversation",
		type: "text",
		label: "系统提示词",
		desc: "对话使用的系统提示词",
		tool: "cli",
	},
	{
		id: "system_prompt_file",
		flag: "-sysf",
		category: "conversation",
		type: "path",
		label: "系统提示词文件",
		desc: "系统提示词所在文件",
		tool: "cli",
	},
	{
		id: "reverse_prompt",
		flag: "-r",
		category: "conversation",
		type: "text",
		label: "反向提示（停止串）",
		desc: "生成到该字符串即停止（交互模式）",
		tool: "both",
	},
	{
		id: "prompt",
		flag: "-p",
		category: "conversation",
		type: "text",
		label: "起始提示",
		desc: "用于开始生成的提示词",
		tool: "cli",
	},
	{
		id: "prompt_file",
		flag: "-f",
		category: "conversation",
		type: "path",
		label: "提示文件",
		desc: "提示词所在文件",
		tool: "cli",
	},
	{
		id: "chat_template",
		flag: "--chat-template",
		category: "conversation",
		type: "enum",
		label: "聊天模板",
		desc: "llama.cpp 内置聊天模板名。要使用模型自带的分词器模板，保持自动即可，需要时可用下方的自定义模板文件。",
		tool: "both",
		options: CHAT_TEMPLATE_PRESET_OPTIONS,
	},
	{
		id: "chat_template_custom",
		flag: "--chat-template-file",
		category: "conversation",
		type: "path",
		label: "自定义模板文件",
		desc: "自定义 Jinja 聊天模板文件路径",
		tool: "both",
	},
	{
		id: "reasoning",
		flag: "-rea",
		category: "conversation",
		type: "enum",
		label: "推理 / 思维",
		desc: "在对话中启用推理/思维",
		tool: "both",
		default: "auto",
		options: [
			{ value: "auto", label: "自动" },
			{ value: "on", label: "开" },
			{ value: "off", label: "关" },
		],
	},
	{
		id: "reasoning_format",
		flag: "--reasoning-format",
		category: "conversation",
		type: "enum",
		label: "推理输出格式",
		desc: "控制思维标签的解析方式。DeepSeek 模式会把思维内容作为独立的推理内容返回，供对话页可折叠的思维面板展示。",
		tool: "both",
		default: "auto",
		options: REASONING_FORMAT_OPTIONS,
	},
	{
		id: "reasoning_budget",
		flag: "--reasoning-budget",
		category: "conversation",
		type: "int",
		label: "思维预算",
		desc: "思维 Token 预算（-1 = 不限，0 = 关闭）",
		tool: "both",
		default: -1,
		min: -1,
	},
	{
		id: "reasoning_budget_message",
		flag: "--reasoning-budget-message",
		category: "conversation",
		type: "text",
		label: "预算耗尽提示语",
		desc: "思维预算耗尽时，在思维结束标签前注入的提示语。",
		tool: "both",
	},
	{
		id: "reasoning_preserve",
		flag: "--reasoning-preserve",
		category: "conversation",
		type: "bool",
		label: "保留推理链",
		desc: "在所选模板支持时，让推理链贯穿完整对话历史保留。推荐对具备 llama.cpp preserve-reasoning 能力的模板开启。",
		tool: "both",
		default: false,
	},
	{
		id: "chat_template_reasoning_effort",
		flag: "--reasoning-effort",
		category: "conversation",
		type: "enum",
		label: "默认推理努力",
		desc: "推理努力——Chat、API 客户端和外部调用共用的服务器级默认值。自动=不发该参数，沿用模型模板默认。llama.cpp b10434+ 使用原生 --reasoning-effort。",
		tool: "server",
		default: "auto",
		options: [
			{ value: "auto", label: "自动" },
			{ value: "low", label: "低" },
			{ value: "medium", label: "中" },
			{ value: "high", label: "高" },
			{ value: "xhigh", label: "超高" },
		],
	},
	{
		id: "preserve_thinking",
		flag: "--chat-template-kwargs",
		category: "conversation",
		type: "bool",
		label: "保留思维（旧版）",
		desc: '旧版模板参数路径：把思维/推理 Token 保留在回复正文中。新版 llama.cpp 请改用“保留推理”。会向聊天模板引擎传 {"preserve_thinking":true}。',
		tool: "both",
		default: false,
	},
	{
		id: "jinja",
		flag: "--jinja",
		category: "conversation",
		type: "bool",
		label: "Jinja 模板",
		desc: "启用基于 Jinja 的聊天模板处理。llama-server 的工具调用/函数调用必须开启。",
		tool: "server",
		default: true,
		false_flag: "--no-jinja",
	},
	{
		id: "single_turn",
		flag: "-st",
		category: "conversation",
		type: "bool",
		label: "单轮模式",
		desc: "运行一轮后退出",
		tool: "cli",
		default: false,
	},
	{
		id: "multiline",
		flag: "-mli",
		category: "conversation",
		type: "bool",
		label: "多行输入",
		desc: "允许无需转义的多行输入",
		tool: "cli",
		default: false,
	},

	// LoRA & Control Vectors
	{
		id: "lora",
		flag: "--lora",
		category: "lora",
		type: "text",
		label: "LoRA 适配器",
		desc: "LoRA 适配器路径（多个用逗号分隔）",
		tool: "both",
	},
	{
		id: "lora_scaled",
		flag: "--lora-scaled",
		category: "lora",
		type: "text",
		label: "LoRA（带缩放）",
		desc: "带缩放的 LoRA 适配器，格式：路径:缩放,…",
		tool: "both",
	},
	{
		id: "control_vector",
		flag: "--control-vector",
		category: "lora",
		type: "text",
		label: "控制向量",
		desc: "控制向量路径（多个用逗号分隔）",
		tool: "both",
	},
	{
		id: "control_vector_scaled",
		flag: "--control-vector-scaled",
		category: "lora",
		type: "text",
		label: "控制向量（带缩放）",
		desc: "带缩放的控制向量，格式：路径:缩放,…",
		tool: "both",
	},
	{
		id: "control_vector_range",
		flag: "--control-vector-layer-range",
		category: "lora",
		type: "text",
		label: "控制向量层范围",
		desc: "控制向量作用层范围：起始 结束",
		tool: "both",
	},

	// KV Cache
	{
		id: "cache_type_k",
		flag: "-ctk",
		category: "kv",
		type: "enum",
		label: "K 缓存类型",
		desc: "K 的 KV 缓存数据类型",
		tool: "both",
		options: CACHE_TYPE_OPTIONS,
	},
	{
		id: "cache_type_v",
		flag: "-ctv",
		category: "kv",
		type: "enum",
		label: "V 缓存类型",
		desc: "V 的 KV 缓存数据类型",
		tool: "both",
		options: CACHE_TYPE_OPTIONS,
	},
	{
		id: "context_shift",
		flag: "--context-shift",
		category: "kv",
		type: "bool",
		label: "上下文轮转",
		desc: "无限生成时使用上下文轮转",
		tool: "both",
		default: false,
	},
	{
		id: "kv_unified",
		flag: "--kv-unified",
		false_flag: "--no-kv-unified",
		category: "kv",
		type: "enum",
		label: "统一 KV 缓存",
		desc: "所有序列共用一个统一 KV 缓冲。启用是 llama.cpp 自动槽位下的常规行为；禁用会发出 --no-kv-unified。",
		tool: "server",
		default: "enabled",
		options: [
			{ value: "enabled", label: "启用" },
			{ value: "disabled", label: "禁用" },
		],
	},

	// Speculative Decoding
	{
		id: "draft_max",
		flag: "--spec-draft-n-max",
		category: "speculative",
		type: "int",
		label: "草稿 Token 数",
		desc: "投机解码每步草稿 Token 数",
		tool: "both",
		min: 0,
		max: 128,
		placeholder: "llama.cpp default",
	},
	{
		id: "draft_min",
		flag: "--spec-draft-n-min",
		category: "speculative",
		type: "int",
		label: "草稿最少 Token",
		desc: "最少草稿 Token 数",
		tool: "both",
		min: 0,
		placeholder: "llama.cpp default",
	},
	{
		id: "draft_p_min",
		flag: "--spec-draft-p-min",
		category: "speculative",
		type: "float",
		label: "草稿最小概率",
		desc: "投机解码最小接受概率（贪心）",
		tool: "both",
		min: 0,
		max: 1,
		step: 0.01,
		placeholder: "llama.cpp default",
	},
	{
		id: "gpu_layers_draft",
		flag: "--spec-draft-ngl",
		category: "speculative",
		type: "text",
		label: "草稿模型 GPU 层数",
		desc: "草稿模型最多放进显存的层数。接受具体数字、auto 或 all。",
		tool: "both",
		placeholder: "auto",
	},
	{
		id: "spec_type",
		flag: "--spec-type",
		category: "speculative",
		type: "enum",
		label: "投机解码类型",
		desc: "投机解码类型",
		tool: "both",
		default: "none",
		options: [
			{ value: "none", label: "无（默认）" },
			{ value: "draft-simple", label: "Draft Simple" },
			{ value: "draft-eagle3", label: "Draft EAGLE-3" },
			{ value: "draft-dflash", label: "Draft DFlash" },
			{ value: "draft-dspark", label: "Draft DSpark" },
			{ value: "draft-mtp", label: "Draft MTP（多 Token 预测）" },
		],
	},
	{
		id: "draft_p_split",
		flag: "--spec-draft-p-split",
		category: "speculative",
		type: "float",
		label: "草稿分裂概率",
		desc: "投机解码分裂概率",
		tool: "both",
		min: 0,
		max: 1,
		step: 0.01,
		placeholder: "llama.cpp default",
	},
	{
		id: "draft_device",
		flag: "-devd",
		category: "speculative",
		type: "text",
		label: "草稿模型设备",
		desc: "草稿模型卸载目标设备，逗号分隔（none = 不卸载）",
		tool: "both",
		placeholder: "auto",
	},
	{
		id: "draft_cache_type_k",
		flag: "-ctkd",
		category: "speculative",
		type: "enum",
		label: "草稿 K 缓存类型",
		desc: "草稿模型 K 的 KV 缓存类型",
		tool: "both",
		options: CACHE_TYPE_OPTIONS,
	},
	{
		id: "draft_cache_type_v",
		flag: "-ctvd",
		category: "speculative",
		type: "enum",
		label: "草稿 V 缓存类型",
		desc: "草稿模型 V 的 KV 缓存类型",
		tool: "both",
		options: CACHE_TYPE_OPTIONS,
	},
	{
		id: "ngram_mod",
		flag: "--spec-type",
		allow_duplicate_cli_flag: true,
		category: "speculative",
		type: "bool",
		label: "Ngram Mod",
		desc: "启用 ngram-mod 投机解码。可与 draft 类型叠加使用。",
		tool: "both",
		default: false,
		submenu: "Ngram Mod",
	},
	{
		id: "ngram_mod_n_match",
		flag: "--spec-ngram-mod-n-match",
		category: "speculative",
		type: "int",
		label: "Ngram 匹配 Token 数",
		desc: "ngram-mod 投机解码的匹配 Token 数（llama.cpp 默认 24）。",
		tool: "both",
		min: 1,
		max: 1024,
		placeholder: "llama.cpp default",
		submenu: "Ngram Mod",
	},
	{
		id: "ngram_mod_n_min",
		flag: "--spec-ngram-mod-n-min",
		category: "speculative",
		type: "int",
		label: "Ngram 最小 Token",
		desc: "ngram-mod 投机解码的最小 Token 数（llama.cpp 默认 48）。",
		tool: "both",
		min: 0,
		max: 1024,
		placeholder: "llama.cpp default",
		submenu: "Ngram Mod",
	},
	{
		id: "ngram_mod_n_max",
		flag: "--spec-ngram-mod-n-max",
		category: "speculative",
		type: "int",
		label: "Ngram 最大 Token",
		desc: "ngram-mod 投机解码的最大 Token 数（llama.cpp 默认 64）。",
		tool: "both",
		min: 0,
		max: 1024,
		placeholder: "llama.cpp default",
		submenu: "Ngram Mod",
	},
	{
		id: "ngram_map_k4v",
		flag: "--spec-type",
		allow_duplicate_cli_flag: true,
		category: "speculative",
		type: "bool",
		label: "Ngram Map K4V",
		desc: "启用 ngram-map-k4v 投机解码：每个 n-gram 键最多跟踪四条草稿续写。可与其他投机类型叠加。",
		tool: "both",
		default: false,
		submenu: "Ngram Map K4V",
	},
	{
		id: "ngram_map_k4v_size_n",
		flag: "--spec-ngram-map-k4v-size-n",
		category: "speculative",
		type: "int",
		label: "查找 N-gram 大小",
		desc: "ngram-map-k4v 投机解码中查找 n-gram 的长度（llama.cpp 默认 12）。",
		tool: "both",
		min: 1,
		max: 1024,
		placeholder: "llama.cpp default",
		submenu: "Ngram Map K4V",
	},
	{
		id: "ngram_map_k4v_size_m",
		flag: "--spec-ngram-map-k4v-size-m",
		category: "speculative",
		type: "int",
		label: "草稿 M-gram 大小",
		desc: "ngram-map-k4v 投机解码中每条草稿 m-gram 的长度（llama.cpp 默认 48）。",
		tool: "both",
		min: 1,
		max: 1024,
		placeholder: "llama.cpp default",
		submenu: "Ngram Map K4V",
	},
	{
		id: "ngram_map_k4v_min_hits",
		flag: "--spec-ngram-map-k4v-min-hits",
		category: "speculative",
		type: "int",
		label: "最少命中次数",
		desc: "ngram-map-k4v 提出草稿前需要的最少查找命中次数（llama.cpp 默认 1）。",
		tool: "both",
		min: 1,
		placeholder: "llama.cpp default",
		submenu: "Ngram Map K4V",
	},

	// Server Settings
	{
		id: "host",
		flag: "--host",
		category: "server",
		type: "text",
		label: "监听地址",
		short_desc: "API 服务器监听的网络地址。",
		desc: "监听的 IP 地址（默认 127.0.0.1）",
		tool: "server",
		default: "127.0.0.1",
	},
	{
		id: "port",
		flag: "--port",
		category: "server",
		type: "int",
		label: "端口",
		short_desc: "API 服务器的端口号。",
		beginner_tip: "Keep 8080 unless another app is already using it.",
		desc: "监听端口",
		tool: "server",
		default: 8080,
		min: 1,
		max: 65535,
	},
	{
		id: "alias",
		flag: "-a",
		category: "server",
		type: "text",
		label: "模型别名",
		desc: "API 使用的模型别名（多个用逗号分隔）",
		tool: "server",
	},
	{
		id: "parallel",
		flag: "-np",
		category: "server",
		type: "int",
		label: "并行槽位数",
		desc: "服务器槽数量（-1 = 自动）",
		tool: "server",
		default: -1,
		min: -1,
		max: 128,
		placeholder: "-1 = auto",
	},
	{
		id: "cont_batching",
		flag: "-cb",
		false_flag: "--no-cont-batching",
		category: "server",
		type: "bool",
		label: "连续批处理",
		desc: "启用动态/连续批处理",
		tool: "server",
		default: true,
	},
	{
		id: "cache_prompt",
		flag: "--cache-prompt",
		false_flag: "--no-cache-prompt",
		category: "server",
		type: "bool",
		label: "提示缓存",
		desc: "启用提示缓存",
		tool: "server",
		default: true,
	},
	{
		id: "cache_idle_slots",
		flag: "--cache-idle-slots",
		false_flag: "--no-cache-idle-slots",
		category: "server",
		type: "bool",
		label: "缓存空闲槽位",
		desc: "新任务到来时把空闲槽位存入提示缓存；统一 KV 模式下会清空（需要缓存内存）",
		tool: "server",
		default: true,
	},
	{
		id: "slot_save_path",
		flag: "--slot-save-path",
		category: "server",
		type: "path",
		label: "槽位缓存保存目录",
		desc: "槽位 KV 缓存状态的保存/恢复目录（可经 API 操作，留空 = 禁用）。目录必须已存在，否则服务器启动失败。",
		tool: "server",
	},
	{
		id: "slots_endpoint",
		flag: "--slots",
		false_flag: "--no-slots",
		category: "server",
		type: "bool",
		label: "槽位监控端点",
		desc: "开放 /slots 监控端点查看各槽位状态",
		tool: "server",
		default: true,
	},
	{
		id: "timeout",
		flag: "-to",
		category: "server",
		type: "int",
		label: "超时（秒）",
		desc: "服务器读写超时",
		tool: "server",
		default: 3600,
		min: 1,
	},
	{
		id: "api_key",
		flag: "--api-key",
		category: "server",
		type: "text",
		label: "API 密钥",
		short_desc: "客户端访问 API 需要的密钥（可选）。",
		desc: "鉴权 API 密钥（多个用逗号分隔）",
		tool: "server",
		sensitive: true,
	},
	{
		id: "threads_http",
		flag: "--threads-http",
		category: "server",
		type: "int",
		label: "HTTP 线程数",
		desc: "HTTP 请求线程数（-1 = 自动）",
		tool: "server",
		min: -1,
	},
	{
		id: "metrics",
		flag: "--metrics",
		category: "server",
		type: "bool",
		label: "Prometheus 指标",
		desc: "启用 Prometheus 指标端点",
		tool: "server",
		default: true,
	},
	{
		id: "webui",
		flag: "--webui",
		false_flag: "--no-webui",
		category: "server",
		type: "bool",
		label: "网页界面",
		short_desc: "开启内置的浏览器界面。",
		desc: "启用内置网页界面",
		tool: "server",
		default: true,
	},
	{
		id: "webui_mcp_proxy",
		flag: "--ui-mcp-proxy",
		category: "mcp",
		type: "bool",
		label: "网页界面 MCP 代理",
		short_desc: "为网页界面启用 MCP CORS 代理。",
		desc: "实验性。允许网页界面通过 CORS 代理 MCP 请求。替代已弃用的 --webui-mcp-proxy。请勿在不受信任的环境中启用。",
		tool: "server",
		default: false,
	},
	{
		id: "tools",
		flag: "--tools",
		category: "mcp",
		type: "multi_enum",
		label: "内置工具",
		short_desc: "在网页界面为 AI 代理启用本地文件/Shell 工具。",
		beginner_tip:
			"Use 'all' only on trusted machines. In shared environments, list only what you need.",
		desc: "实验性。启用 llama-server 暴露给模型的内置代理工具。在下方选择一个或多个工具，或选 all 启用全部。",
		tool: "server",
		options: [
			{ value: "all", label: "全部工具", risk: "high" },
			{ value: "read_file", label: "读取文件" },
			{ value: "file_glob_search", label: "文件通配符搜索" },
			{ value: "grep_search", label: "内容搜索" },
			{
				value: "exec_shell_command",
				label: "执行 Shell 命令",
				risk: "high",
			},
			{ value: "write_file", label: "写入文件", risk: "high" },
			{ value: "edit_file", label: "编辑文件", risk: "high" },
			{ value: "get_datetime", label: "获取日期时间" },
		],
	},
	{
		id: "embedding",
		flag: "--embedding",
		category: "server",
		type: "bool",
		label: "嵌入模式",
		desc: "仅限嵌入（embedding）用途",
		tool: "server",
		default: false,
	},
	{
		id: "slot_prompt_similarity",
		flag: "-sps",
		category: "server",
		type: "float",
		label: "槽位复用相似度阈值",
		desc: "槽位复用的提示相似度阈值（0 = 关闭）",
		tool: "server",
		default: 0.1,
		min: 0,
		max: 1,
		step: 0.01,
	},
	{
		id: "cache_reuse",
		flag: "--cache-reuse",
		category: "server",
		type: "int",
		label: "缓存复用块大小",
		desc: "KV 轮转复用缓存的最小块大小（0 = 关闭）",
		tool: "server",
		default: 0,
		min: 0,
	},

	// Grammar & Constraints
	{
		id: "grammar",
		flag: "--grammar",
		category: "grammar",
		type: "text",
		label: "语法约束",
		desc: "类 BNF 语法，约束生成内容",
		tool: "both",
	},
	{
		id: "grammar_file",
		flag: "--grammar-file",
		category: "grammar",
		type: "path",
		label: "语法文件",
		desc: "语法规则所在文件",
		tool: "both",
	},
	{
		id: "json_schema",
		flag: "-j",
		category: "grammar",
		type: "text",
		label: "JSON 模式",
		desc: "约束输出的 JSON 模式，例如 {}",
		tool: "both",
	},
	{
		id: "json_schema_file",
		flag: "-jf",
		category: "grammar",
		type: "path",
		label: "JSON 模式文件",
		desc: "JSON 模式所在文件",
		tool: "both",
	},
	{
		id: "backend_sampling",
		flag: "-bs",
		category: "grammar",
		type: "bool",
		label: "后端采样",
		desc: "启用后端采样（实验性）",
		tool: "both",
		default: false,
	},

	// Logging
	{
		id: "verbose",
		flag: "-v",
		category: "logging",
		type: "bool",
		label: "详细日志",
		desc: "日志详细度拉满（输出所有消息）",
		tool: "both",
		default: false,
	},
	{
		id: "verbosity",
		flag: "-lv",
		category: "logging",
		type: "int",
		label: "日志级别",
		desc: "日志详细度阈值（0=常规，1=错误，2=警告，3=信息，4=调试）",
		tool: "both",
		default: 3,
		min: 0,
		max: 4,
	},
	{
		id: "log_file",
		flag: "--log-file",
		category: "logging",
		type: "path",
		label: "日志文件",
		desc: "日志写入文件",
		tool: "both",
	},
	{
		id: "log_colors",
		flag: "--log-colors",
		category: "logging",
		type: "enum",
		label: "日志彩色",
		desc: "彩色日志",
		tool: "both",
		default: "auto",
		options: [
			{ value: "auto", label: "自动（默认）" },
			{ value: "on", label: "开" },
			{ value: "off", label: "关" },
		],
	},
	{
		id: "log_prefix",
		flag: "--log-prefix",
		category: "logging",
		type: "bool",
		label: "日志前缀",
		desc: "日志消息加前缀",
		tool: "both",
		default: false,
	},
	{
		id: "log_timestamps",
		flag: "--log-timestamps",
		category: "logging",
		type: "bool",
		label: "日志时间戳",
		desc: "日志消息加时间戳",
		tool: "both",
		default: false,
	},
	{
		id: "show_timings",
		flag: "--show-timings",
		false_flag: "--no-show-timings",
		category: "logging",
		type: "bool",
		label: "显示耗时",
		desc: "每条回复后显示耗时信息",
		tool: "cli",
		default: true,
	},

	// Advanced
	{
		id: "override_kv",
		flag: "--override-kv",
		category: "advanced",
		type: "text",
		label: "覆盖 KV 元数据",
		desc: "覆盖模型元数据，例如 KEY=TYPE:VALUE,…",
		tool: "both",
	},
	{
		id: "override_tensor",
		flag: "-ot",
		category: "advanced",
		type: "text",
		label: "张量缓冲覆盖",
		short_desc:
			"把匹配的模型张量强制放到指定后端缓冲，例如 CPU 或 CUDA0。",
		desc: "专家级张量显存布局覆盖。格式：模式=缓冲区，多个用逗号分隔。模式按 GGUF/磁盘上的张量名匹配（常用正则式转义），命中的张量会被强制放入指定缓冲区。",
		tool: "both",
		placeholder: "blk.*.ffn_.*_exps.weight=CPU",
	},
	{
		id: "check_tensors",
		flag: "--check-tensors",
		category: "advanced",
		type: "bool",
		label: "校验张量",
		desc: "检查模型张量数据中的非法值",
		tool: "both",
		default: false,
	},
	{
		id: "no_host",
		flag: "--no-host",
		category: "advanced",
		type: "bool",
		label: "禁用主机缓冲",
		desc: "额外缓冲绕过主机缓冲",
		tool: "both",
		default: false,
	},
	{
		id: "warmup",
		flag: "--warmup",
		false_flag: "--no-warmup",
		category: "advanced",
		type: "bool",
		label: "预热",
		desc: "启动时用空跑做预热",
		tool: "both",
		default: true,
	},
	{
		id: "offline",
		flag: "--offline",
		category: "advanced",
		type: "bool",
		label: "离线模式",
		desc: "强制使用缓存，禁止访问网络",
		tool: "both",
		default: false,
	},

	// Experimental
	{
		id: "spec_draft_adaptive",
		flag: "--spec-draft-adaptive",
		category: "experimental",
		type: "bool",
		label: "自适应草稿数",
		desc: "按实测接受率决定每步草稿数量，而不是总是按 --spec-draft-n-max 取满。仅 LaurentZuijdwijk llama.cpp 分支可用；官方构建可能拒绝该参数。",
		tool: "both",
		default: false,
	},
];
