const CHAT_SAMPLER_SLIDER_MAP = {
    "chat-slider-temp": { flag: "temperature", decimals: 2 },
    "chat-slider-top-p": { flag: "top_p", decimals: 2 },
    "chat-slider-top-k": { flag: "top_k", decimals: 0 },
    "chat-slider-min-p": { flag: "min_p", decimals: 2 },
    "chat-slider-repeat": { flag: "repeat_penalty", decimals: 2 },
    "chat-slider-max-tokens": { flag: "n_predict", decimals: 0 },
};

const SAMPLER_PRESET_STORAGE_KEY = "llama_gui_sampler_presets_v1";
const BUILTIN_SAMPLER_PRESETS = {
    Neutral: {
        temperature: 1.0,
        top_k: 200,
        top_p: 1.0,
        min_p: 0,
        top_n_sigma: -1,
        xtc_probability: 0,
        xtc_threshold: 1.0,
        typical_p: 1.0,
        repeat_last_n: 64,
        repeat_penalty: 1.0,
        presence_penalty: 0,
        frequency_penalty: 0,
        dry_multiplier: 0,
        dynatemp_range: 0,
        mirostat: "0",
    },
    Balanced: {
        temperature: 1.0,
        top_k: 0,
        top_p: 0.95,
        min_p: 0.1,
        top_n_sigma: -1,
        xtc_probability: 0,
        xtc_threshold: 1.0,
        typical_p: 1.0,
        repeat_last_n: 64,
        repeat_penalty: 1.03,
        presence_penalty: 0,
        frequency_penalty: 0,
        dry_multiplier: 0,
        dry_base: 1.75,
        dry_allowed_length: 2,
        dynatemp_range: 0,
        dynatemp_exp: 1.0,
        mirostat: "0",
        mirostat_lr: 0.1,
        mirostat_ent: 5,
        seed: -1,
        ignore_eos: false,
    },
    Creative: {
        temperature: 1.0,
        top_k: 100,
        top_p: 0.98,
        min_p: 0,
        repeat_penalty: 1.1,
        repeat_last_n: 64,
    },
    Precise: {
        temperature: 0.3,
        top_k: 25,
        top_p: 0.6,
        min_p: 0,
        repeat_penalty: 1.02,
        repeat_last_n: 64,
    },
};

const QUICK_CONTEXT_PRESETS = ["8192", "16000", "32768", "64000", "128000", "256000"];
const QUICK_PROFILES = {
    "safe-defaults": {
        label: "Safe Defaults",
        summary: "Applies a full starter setup: 16000 context, Auto Fit on, GPU offload on auto, and balanced sampler settings.",
        tool: "llama-server",
        flags: {
            ctx_size: 16000,
            gpu_layers: "auto",
            fit: "on",
            fit_target: "1024",
            fit_ctx: 16000,
            temperature: 0.8,
            top_p: 0.95,
            min_p: 0.05,
            repeat_penalty: 1.05,
        },
        samplerPresetName: "Balanced",
    },
    balanced: {
        label: "Balanced",
        summary: "Applies a full general-purpose setup with 32768 context, Auto Fit, auto GPU offload, and the Balanced sampler preset.",
        tool: "llama-server",
        flags: {
            ctx_size: 32768,
            gpu_layers: "auto",
            fit: "on",
            fit_target: "1024",
            fit_ctx: 32768,
            temperature: 0.8,
            top_p: 0.95,
            min_p: 0.05,
            repeat_penalty: 1.05,
        },
        samplerPresetName: "Balanced",
    },
    "long-context": {
        label: "Long Context",
        summary: "Applies a 128000 context window while keeping Auto Fit active and the rest of the launch settings beginner-friendly.",
        tool: "llama-server",
        flags: {
            ctx_size: 128000,
            gpu_layers: "auto",
            fit: "on",
            fit_target: "1024",
            fit_ctx: 128000,
            temperature: 0.75,
            top_p: 0.95,
            min_p: 0.04,
            repeat_penalty: 1.05,
        },
        samplerPresetName: "Balanced",
    },
    "creative-chat": {
        label: "Creative Chat",
        summary: "Applies a 32768 context setup, then warms up the sampler for more creative and open-ended responses.",
        tool: "llama-server",
        flags: {
            ctx_size: 32768,
            gpu_layers: "auto",
            fit: "on",
            fit_target: "1024",
            fit_ctx: 32768,
            temperature: 1.05,
            top_p: 0.97,
            min_p: 0.03,
            repeat_penalty: 1.02,
        },
        samplerPresetName: "Creative",
    },
};
