// Presets package (10/10): public window.LlamaGui.presets namespace assembly. Loaded last.
if (window.LlamaGui) {
    window.LlamaGui.presets = Object.assign(window.LlamaGui.presets || {}, {
        configure: configurePresetModule,
        loadPreset,
        matchesCurrentPreset,
        comparePresetToCurrent,
        formatSavedPresetValue,
        initContextControls: initPresetContextControls,
        refreshContext: refreshPresetContext,
        getLastLoadedPresetName: () => lastLoadedPresetName,
        isPresetFavorite,
        getPresetLastUsed,
        fetchPresetEntries,
        findPresetByName,
        normalizePresetData,
        normalizeImportedPresetData,
        sanitizeImportedPresetName,
        findPresetImportNameCollision,
        getPresetWarnings,
        isPresetModelMissing,
        getPresetModelIssue,
        matchKnownModelName,
        resolvePresetModelName,
        applyPresetModel,
        getPresetModelFileName,
        getPresetLibrarySummary,
        getPresetHealthMessage,
        buildPresetSearchText,
        getPresetFlagLabel,
        refreshModelPresence,
        getPresetFocusItems,
        applyPresetRovingTabIndex,
        movePresetRovingFocus,
        formatPresetTimestamp,
        isFullPresetData,
        preparePresetLaunchState,
        applyPresetData,
        stripSensitivePresetFlags,
        hasSensitiveCustomArgs,
    });
}
